import '@/styles/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Navbar from "@/components/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Reaction Time Test',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <link rel='icon' href='/favicon.ico'/>
        </head>
        <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
        </html>
    )
}
